### ISSUE TITLE
Definir stack 🧰

### ISSUE THREAD

**Issue by JaviCeRodriguez** [discode-sv/discode-page#1]
Este issue nos va a ser como prueba para el tablero en Projects.

De paso, debemos elegir un stack a utilizar junto con Gatsby. Tenemos esto:

**Framework CSS**: TalwindCSS, Styled Components, Sass
**Framework UI**: Semantic, Ant Design, Material UI

Dejar como comentario la decisión final. También se puede definir otro framework que no haya sido mencionado anteriormente

**Comment by nicolasvazquezdev** [comment]
Framework CSS

**Comment by discode-sv** [comment]
Cerramos con Gatsby + Styled Components
